import React, { useState } from "react";
import { motion, easeOut } from "framer-motion";
import { useNavigate } from "react-router-dom";
import { SignInButton, useAuth } from "@clerk/clerk-react";
import {
  Check,
  Zap,
  Crown,
  Rocket,
  ArrowRight,
  Star,
  Users,
  BarChart2,
  Sparkles,
  Globe,
  Lock,
  MessageCircle,
  Infinity,
} from "lucide-react";
import { Helmet } from "react-helmet-async";

/* ─────────────────────────── data ─────────────────────────── */

const PLANS = [
  {
    id: "free",
    name: "Reader",
    tagline: "Perfect for casual readers & first-time writers.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    icon: Star,
    accent: "gray",
    accentBg: "bg-gray-900",
    accentText: "text-white",
    badge: null,
    cta: "Start for Free",
    features: [
      { text: "Unlimited reading of all public articles", icon: Check },
      { text: "Bookmark & like articles", icon: Check },
      { text: "Personalised Explore feed", icon: Check },
      { text: "Comment on any article", icon: Check },
      { text: "Publish up to 3 articles / month", icon: Check },
      { text: "Basic profile page", icon: Check },
      { text: "Standard support (community)", icon: Check },
    ],
    locked: [
      "Analytics dashboard",
      "AI writing assistant",
      "Ad-free reading",
      "Custom domain",
      "Monetisation",
    ],
  },
  {
    id: "pro",
    name: "Dock Pro",
    tagline: "For serious writers who want to grow an audience.",
    monthlyPrice: 8,
    yearlyPrice: 72,
    icon: Zap,
    accent: "indigo",
    accentBg: "bg-indigo-600",
    accentText: "text-white",
    badge: "Most Popular",
    cta: "Get Dock Pro",
    features: [
      { text: "Everything in Reader", icon: Check },
      { text: "Unlimited article publishing", icon: Infinity },
      { text: "Analytics dashboard (views, reads, likes)", icon: BarChart2 },
      { text: "AI writing assistant (rewrite, continue, summarise)", icon: Sparkles },
      { text: "Ad-free reading experience", icon: Check },
      { text: "Collaborate with up to 3 co-authors", icon: Users },
      { text: "Series creation & organisation", icon: Check },
      { text: "Priority placement in Explore feed", icon: Rocket },
      { text: "Custom author profile & bio link", icon: Check },
      { text: "Priority email support", icon: MessageCircle },
    ],
    locked: ["Custom domain", "API access", "Remove DraftDock branding"],
  },
  {
    id: "elite",
    name: "Dock Elite",
    tagline: "For power users, teams, and professional publishers.",
    monthlyPrice: 16,
    yearlyPrice: 144,
    icon: Crown,
    accent: "violet",
    accentBg: "bg-gradient-to-br from-violet-600 to-violet-800",
    accentText: "text-white",
    badge: "Best Value",
    cta: "Go Elite",
    features: [
      { text: "Everything in Dock Pro", icon: Check },
      { text: "Unlimited co-authors per article", icon: Users },
      { text: "Monetisation & Partner Revenue Share", icon: BarChart2 },
      { text: "Custom domain (yourname.com)", icon: Globe },
      { text: "Remove DraftDock branding", icon: Check },
      { text: "Full REST API access", icon: Check },
      { text: "Export articles (PDF, Markdown, HTML)", icon: Check },
      { text: "Publication management (team workspace)", icon: Check },
      { text: "Leaderboard visibility boost", icon: Rocket },
      { text: "Early access to new features & beta", icon: Sparkles },
      { text: "Dedicated account manager", icon: MessageCircle },
    ],
    locked: [],
  },
];

const FAQ = [
  {
    q: "Can I switch plans at any time?",
    a: "Yes. You can upgrade, downgrade, or cancel at any time. Changes take effect at the end of your current billing cycle.",
  },
  {
    q: "Is there a free trial for paid plans?",
    a: "Dock Pro comes with a 14-day free trial — no credit card required. Try all Pro features risk-free.",
  },
  {
    q: "What payment methods are accepted?",
    a: "We accept all major credit/debit cards (Visa, Mastercard, Amex) and PayPal. Yearly plans are billed upfront at a discount.",
  },
  {
    q: "How does the monetization work for Elite?",
    a: "Elite members who join our Partner Programme earn a share of ad and subscription revenue generated by their articles, paid out monthly.",
  },
  {
    q: "Do free articles stay free forever?",
    a: "All articles you publish on the Free plan remain fully live and readable. If you downgrade from Pro/Elite, articles above the 3/month cap are preserved but hidden until you upgrade again.",
  },
];

/* ─────────────────────────── helpers ─────────────────────────── */

const reveal = {
  hidden: { opacity: 0, y: 28 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.7, ease: easeOut } },
};

const stagger = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.15 } },
};

/* ─────────────────────────── component ─────────────────────────── */

const PricingPage: React.FC = () => {
  const [annual, setAnnual] = useState(true);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const navigate = useNavigate();
  const { isSignedIn } = useAuth();

  return (
    <div className="min-h-screen bg-[#f8f9fa] dark:bg-gray-950 text-gray-900 dark:text-white">
      <Helmet>
        <title>Pricing — DraftDock</title>
        <meta
          name="description"
          content="Choose a DraftDock plan. Free, Pro, or Elite — there's a tier for every kind of writer."
        />
      </Helmet>

      {/* ── Hero ── */}
      <motion.header
        className="pt-20 pb-14 px-6 text-center"
        variants={stagger}
        initial="hidden"
        animate="visible"
      >
        <motion.div variants={reveal}>
          <span className="inline-flex items-center gap-2 px-4 py-1.5 bg-indigo-100 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400 rounded-full text-xs font-label font-bold uppercase tracking-widest mb-6">
            <Zap size={12} />
            Simple, transparent pricing
          </span>
        </motion.div>
        <motion.h1
          variants={reveal}
          className="text-5xl md:text-6xl font-headline font-bold tracking-tighter leading-none mb-4"
        >
          Write more. Earn more.
          <br />
          <span className="text-indigo-600 dark:text-indigo-400">Scale your voice.</span>
        </motion.h1>
        <motion.p
          variants={reveal}
          className="text-gray-500 dark:text-gray-400 max-w-xl mx-auto font-body text-lg mb-10"
        >
          Start free. Upgrade when you're ready. No hidden fees, no lock-in.
        </motion.p>

        {/* Billing toggle */}
        <motion.div variants={reveal} className="inline-flex items-center gap-4">
          <span
            className={`text-sm font-label font-bold ${!annual ? "text-gray-900 dark:text-white" : "text-gray-400"}`}
          >
            Monthly
          </span>
          <button
            onClick={() => setAnnual(!annual)}
            className={`relative inline-flex h-7 w-14 items-center rounded-full transition-colors ${
              annual ? "bg-indigo-600" : "bg-gray-300 dark:bg-gray-700"
            }`}
          >
            <span
              className={`inline-block w-5 h-5 transform rounded-full bg-white shadow-sm transition-transform duration-300 ${
                annual ? "translate-x-8" : "translate-x-1"
              }`}
            />
          </button>
          <span
            className={`text-sm font-label font-bold flex items-center gap-2 ${annual ? "text-gray-900 dark:text-white" : "text-gray-400"}`}
          >
            Annual
            <span className="px-2 py-0.5 bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400 rounded-full text-[10px] font-black uppercase tracking-wider">
              Save 25%
            </span>
          </span>
        </motion.div>
      </motion.header>

      {/* ── Plans Grid ── */}
      <motion.section
        className="px-6 pb-20 max-w-6xl mx-auto"
        variants={stagger}
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, amount: 0.1 }}
      >
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-stretch">
          {PLANS.map((plan) => {
            const Icon = plan.icon;
            const monthlyEquiv = annual
              ? plan.yearlyPrice === 0
                ? 0
                : Math.round((plan.yearlyPrice / 12) * 10) / 10
              : plan.monthlyPrice;
            const isElite = plan.id === "elite";

            return (
              <motion.div
                key={plan.id}
                variants={reveal}
                className={`relative flex flex-col rounded-3xl border overflow-hidden transition-shadow hover:shadow-2xl ${
                  isElite
                    ? "border-violet-400/60 dark:border-violet-600/60 shadow-xl shadow-violet-200/20 dark:shadow-violet-900/20"
                    : plan.id === "pro"
                    ? "border-indigo-300/60 dark:border-indigo-700/60 shadow-lg shadow-indigo-100/30 dark:shadow-none"
                    : "border-gray-200 dark:border-gray-800 shadow-sm"
                } bg-white dark:bg-gray-900`}
              >
                {/* Badge */}
                {plan.badge && (
                  <div
                    className={`absolute top-5 right-5 px-3 py-1 rounded-full text-[10px] font-label font-black uppercase tracking-widest ${
                      isElite
                        ? "bg-violet-100 dark:bg-violet-900/40 text-violet-600 dark:text-violet-300"
                        : "bg-indigo-100 dark:bg-indigo-900/40 text-indigo-600 dark:text-indigo-300"
                    }`}
                  >
                    {plan.badge}
                  </div>
                )}

                {/* Header */}
                <div
                  className={`p-7 ${
                    isElite
                      ? "bg-gradient-to-br from-violet-600 to-violet-800"
                      : plan.id === "pro"
                      ? "bg-indigo-600"
                      : "bg-gray-900"
                  } text-white`}
                >
                  <div className="flex items-center gap-3 mb-4">
                    <div className="p-2 bg-white/10 rounded-xl">
                      <Icon size={20} />
                    </div>
                    <h2 className="text-xl font-headline font-bold">{plan.name}</h2>
                  </div>
                  <div className="mb-2">
                    {plan.monthlyPrice === 0 ? (
                      <span className="text-5xl font-headline font-black">Free</span>
                    ) : (
                      <>
                        <span className="text-5xl font-headline font-black">
                          ${monthlyEquiv}
                        </span>
                        <span className="text-white/70 text-sm font-label ml-1">/mo</span>
                      </>
                    )}
                  </div>
                  {plan.yearlyPrice > 0 && annual && (
                    <p className="text-white/60 text-xs font-label">
                      Billed ${plan.yearlyPrice}/year · saves ${plan.monthlyPrice * 12 - plan.yearlyPrice}/yr
                    </p>
                  )}
                  {plan.yearlyPrice > 0 && !annual && (
                    <p className="text-white/60 text-xs font-label">
                      Or ${plan.yearlyPrice}/year — save ${plan.monthlyPrice * 12 - plan.yearlyPrice}
                    </p>
                  )}
                  <p className="text-white/70 text-sm font-body mt-3 leading-relaxed">
                    {plan.tagline}
                  </p>
                </div>

                {/* Features */}
                <div className="flex-1 p-7 space-y-3">
                  {plan.features.map(({ text, icon: FeatureIcon }) => (
                    <div key={text} className="flex items-start gap-3">
                      <div
                        className={`flex-shrink-0 mt-0.5 p-0.5 rounded-full ${
                          isElite
                            ? "text-violet-600 dark:text-violet-400"
                            : plan.id === "pro"
                            ? "text-indigo-600 dark:text-indigo-400"
                            : "text-gray-600 dark:text-gray-400"
                        }`}
                      >
                        <FeatureIcon size={15} />
                      </div>
                      <span className="text-sm text-gray-700 dark:text-gray-300 font-body leading-snug">
                        {text}
                      </span>
                    </div>
                  ))}

                  {plan.locked.length > 0 && (
                    <>
                      <div className="border-t border-gray-100 dark:border-gray-800 pt-3 mt-3">
                        {plan.locked.map((text) => (
                          <div key={text} className="flex items-start gap-3 mb-3">
                            <Lock
                              size={14}
                              className="flex-shrink-0 mt-0.5 text-gray-300 dark:text-gray-700"
                            />
                            <span className="text-sm text-gray-300 dark:text-gray-600 font-body line-through leading-snug">
                              {text}
                            </span>
                          </div>
                        ))}
                      </div>
                    </>
                  )}
                </div>

                {/* CTA */}
                <div className="px-7 pb-7">
                  {plan.monthlyPrice === 0 ? (
                    isSignedIn ? (
                      <button
                        onClick={() => navigate("/explore")}
                        className="w-full py-3 rounded-xl font-label font-bold text-sm uppercase tracking-widest bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-white hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors flex items-center justify-center gap-2"
                      >
                        {plan.cta} <ArrowRight size={14} />
                      </button>
                    ) : (
                      <SignInButton mode="modal">
                        <button className="w-full py-3 rounded-xl font-label font-bold text-sm uppercase tracking-widest bg-gray-100 dark:bg-gray-800 text-gray-900 dark:text-white hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors flex items-center justify-center gap-2">
                          {plan.cta} <ArrowRight size={14} />
                        </button>
                      </SignInButton>
                    )
                  ) : (
                    <button
                      onClick={() => navigate("/contact")}
                      className={`w-full py-3 rounded-xl font-label font-bold text-sm uppercase tracking-widest transition-all flex items-center justify-center gap-2 active:scale-95 ${
                        isElite
                          ? "bg-gradient-to-r from-violet-600 to-violet-700 text-white hover:opacity-90 shadow-lg shadow-violet-200/30 dark:shadow-none"
                          : "bg-indigo-600 text-white hover:bg-indigo-700 shadow-lg shadow-indigo-200/30 dark:shadow-none"
                      }`}
                    >
                      {plan.cta} <ArrowRight size={14} />
                    </button>
                  )}
                </div>
              </motion.div>
            );
          })}
        </div>
      </motion.section>

      {/* ── Comparison callout ── */}
      <motion.section
        className="py-16 px-6 max-w-4xl mx-auto text-center"
        variants={stagger}
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, amount: 0.2 }}
      >
        <motion.div
          variants={reveal}
          className="bg-white dark:bg-gray-900 border border-gray-200/80 dark:border-gray-800 rounded-3xl p-10 md:p-14 shadow-sm"
        >
          <span className="text-[10px] font-label font-black uppercase tracking-[0.2em] text-gray-400 mb-4 block">
            Why DraftDock Pro?
          </span>
          <h2 className="text-3xl md:text-4xl font-headline font-bold tracking-tighter mb-6">
            Half the price of Medium Premium.
            <br />
            <span className="text-indigo-600 dark:text-indigo-400">Twice the tools.</span>
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-10">
            {[
              {
                label: "vs Medium",
                price: "$9.99/mo",
                color: "text-red-500",
                note: "Reader-only. Writers get no analytics.",
              },
              {
                label: "DraftDock Pro",
                price: "$8/mo",
                color: "text-indigo-600 dark:text-indigo-400",
                note: "Full writer suite + analytics + AI.",
                highlight: true,
              },
              {
                label: "vs Substack Pro",
                price: "10% revenue cut",
                color: "text-red-500",
                note: "Commission-based, no fixed pricing.",
              },
            ].map((c) => (
              <div
                key={c.label}
                className={`p-6 rounded-2xl border ${
                  c.highlight
                    ? "border-indigo-300 dark:border-indigo-700 bg-indigo-50 dark:bg-indigo-900/20"
                    : "border-gray-200 dark:border-gray-800 bg-gray-50 dark:bg-gray-800/50"
                }`}
              >
                <p className="text-xs font-label font-bold uppercase tracking-widest text-gray-400 mb-2">
                  {c.label}
                </p>
                <p className={`text-2xl font-headline font-black mb-2 ${c.color}`}>{c.price}</p>
                <p className="text-xs text-gray-400 font-body leading-relaxed">{c.note}</p>
              </div>
            ))}
          </div>
        </motion.div>
      </motion.section>

      {/* ── FAQ ── */}
      <section className="py-16 px-6 max-w-3xl mx-auto">
        <motion.div
          variants={stagger}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.15 }}
        >
          <motion.div variants={reveal} className="mb-10 text-center">
            <span className="text-[10px] font-label font-black uppercase tracking-[0.2em] text-gray-400 block mb-2">
              Got questions?
            </span>
            <h2 className="text-3xl font-headline font-bold tracking-tighter">
              Frequently Asked
            </h2>
          </motion.div>

          <div className="space-y-3">
            {FAQ.map((item, i) => (
              <motion.div
                key={i}
                variants={reveal}
                className="bg-white dark:bg-gray-900 border border-gray-200/80 dark:border-gray-800 rounded-2xl overflow-hidden"
              >
                <button
                  className="w-full text-left px-6 py-5 flex items-center justify-between gap-4"
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                >
                  <span className="font-headline font-bold text-gray-900 dark:text-white text-sm">
                    {item.q}
                  </span>
                  <span
                    className={`flex-shrink-0 transition-transform duration-300 text-gray-400 ${
                      openFaq === i ? "rotate-45" : ""
                    }`}
                  >
                    +
                  </span>
                </button>
                <motion.div
                  initial={false}
                  animate={{ height: openFaq === i ? "auto" : 0, opacity: openFaq === i ? 1 : 0 }}
                  transition={{ duration: 0.3, ease: "easeInOut" }}
                  className="overflow-hidden"
                >
                  <p className="px-6 pb-5 text-sm text-gray-500 dark:text-gray-400 font-body leading-relaxed">
                    {item.a}
                  </p>
                </motion.div>
              </motion.div>
            ))}
          </div>
        </motion.div>
      </section>

      {/* ── CTA Banner ── */}
      <motion.section
        className="py-20 px-6"
        variants={stagger}
        initial="hidden"
        whileInView="visible"
        viewport={{ once: true, amount: 0.3 }}
      >
        <motion.div
          variants={reveal}
          className="max-w-4xl mx-auto bg-gradient-to-br from-indigo-600 to-violet-700 rounded-3xl p-12 md:p-16 text-center text-white shadow-2xl shadow-indigo-200/30 dark:shadow-none"
        >
          <h2 className="text-4xl md:text-5xl font-headline font-bold tracking-tighter mb-4">
            Start writing today.
          </h2>
          <p className="text-white/70 max-w-md mx-auto font-body mb-10 text-lg">
            Join thousands of technical writers already building their audience on DraftDock.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            {isSignedIn ? (
              <button
                onClick={() => navigate("/create-blog")}
                className="px-8 py-4 bg-white text-indigo-700 rounded-xl font-label font-bold text-sm uppercase tracking-widest hover:bg-gray-50 transition-colors flex items-center gap-2 justify-center"
              >
                Start Drafting <ArrowRight size={16} />
              </button>
            ) : (
              <SignInButton mode="modal">
                <button className="px-8 py-4 bg-white text-indigo-700 rounded-xl font-label font-bold text-sm uppercase tracking-widest hover:bg-gray-50 transition-colors flex items-center gap-2 justify-center">
                  Get Started Free <ArrowRight size={16} />
                </button>
              </SignInButton>
            )}
            <button
              onClick={() => navigate("/explore")}
              className="px-8 py-4 border-2 border-white/40 text-white rounded-xl font-label font-bold text-sm uppercase tracking-widest hover:border-white/80 transition-colors"
            >
              Browse Articles
            </button>
          </div>
        </motion.div>
      </motion.section>
    </div>
  );
};

export default PricingPage;
