# Auto-generated by Terraform — do not edit manually.
# Re-generated on every `terraform apply`.
[draftdock]
<EC2_PUBLIC_IP> ansible_user=ubuntu ansible_ssh_private_key_file=../.key/draftdock.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'
